#!/usr/bin/env bash
# Displays a list of currently running processes
# Options: f, full-format; a, all process; x, all processes owned by you
# u, user-oriented format
# Use command grep that print lines matching a pattern
ps -fuax | grep "bash"
# To prevent shellcheck from processing one directive
# shellcheck disable=SC2009